irdb/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('staticpages.urls')),
    path('restaurants/', include('restaurants.urls')), # adicionar esta linha
    path('accounts/', include('accounts.urls')), # adicionar esta linha
    path('accounts/', include('django.contrib.auth.urls')), # adicione esta linha
    path('admin/', admin.site.urls),
]

restaurants/urls.py
from django.urls import path

from . import views


app_name = 'restaurants'
urlpatterns = [
    path('', views.RestaurantListView.as_view(), name='index'),
    path('search/', views.search_restaurants , name='search'),
    path('create/', views.create_restaurant, name='create'),
    path('minhasreservas/<int:user_id>/', views.minhas_reserva, name='minhasreservas'),
    path('<int:restaurant_id>/reserva/', views.reserva_restaurant, name='reserva'),
    path('<int:restaurant_id>/reservacreate', views.create_reserva, name='reservacreate'),
    path('<int:reserva_id>/reservaup', views.update_reserva, name='reservaup'),
    path('meurestaurante/<int:user_id>/', views.meu_restaurant, name='meurestaurante'),
    path('<int:restaurant_id>/', views.detail_restaurant, name='detail'),
    #path('submit_resenha/<int:restaurant_id>/', views.submit_resenha, name='submit_resenha'),
    path('update/<int:restaurant_id>/', views.update_restaurant, name='update'),
    path('delete/<int:restaurant_id>/', views.delete_restaurant, name='delete'),
    path('<int:restaurant_id>/resenha/', views.create_resenha, name='resenha'),
]

restaurants/models.py
from django.db import models

# Create your models here.
from django.conf import settings
from django.db.models import Avg
from django.contrib.auth.models import User
from cpf_field.models import CPFField

class Restaurant(models.Model):
    name = models.CharField(max_length=255)
    poster_url = models.URLField(max_length=200, null=True)
    author_id = models.IntegerField(default=0)
    endereco = models.CharField(max_length=255, blank= True)
    comida = models.CharField(max_length=255, blank= True)
    preco = models.CharField(max_length=255, blank= True)
    text = models.TextField(max_length=500, blank= True)
    avr = models.FloatField(default=0)
    
    def average_rating(self) -> float:
        return Resenha.objects.filter(restaurant=self).aggregate(Avg("rating"))["rating__avg"] or 0

    def __str__(self):
        return f'{self.name}'
    

class Resenha(models.Model):
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    text = models.TextField(max_length=500, blank= True)
    likes = models.IntegerField(default=0)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    rating = models.FloatField(default=0)
    data=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'"{self.text}" - {self.author.username}'

class Reserva (models.Model):
    cliente = models.ForeignKey(User,on_delete=models.CASCADE)
    cpf = CPFField('cpf')
    np = models.IntegerField(default=0)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    data_up=models.DateTimeField(auto_now_add=True)
    reserva=models.DateTimeField('%Y-%m-%d %H:%M')
    standby = models.BooleanField(default=False)
    aprove = models.BooleanField(default=False)

    def __str__(self):
        return f'"{self.cliente}" - {self.restaurant}'

restaurants/forms.py
from django.forms import ModelForm
from .models import Restaurant, Resenha, Reserva


class RestaurantForm(ModelForm):
    class Meta:
        model = Restaurant
        fields = [
            'name',
            'poster_url',
            'endereco',
            'comida',
            'preco',
            'text',
        ]
        labels = {
            'name': 'Nome do Restaurante',
            'poster_url': 'URL do logo',
            'endereco': 'Endereço',
            'comida': 'Tipo de comida',
            'preco': 'Faixa de preço',
            'text': 'Descrição do lugar',
        }

class ResenhaForm(ModelForm):
    class Meta:
        model = Resenha
        fields = [
            
            'text',
            'rating',
        ]
        labels = {
            'author': 'Usuário',
            'text': 'Resenha',
        }

class ReservaForm(ModelForm):
    class Meta:
        model = Reserva
        fields = [
            
            'cpf',
            'np',
            'reserva',
        ]
        labels = {
            'cpf': 'CPF',
            'np': 'Número de pessoas',
            'reserva': 'Dia  e hora da reserva: (Mês/Dia/Ano xx:xx)  ',
        }

class ReservaUpdateForm(ModelForm):
    class Meta:
        model = Reserva
        fields = [
            
            'aprove',
            
            
        ]
        labels = {
            'aprove': 'Aprovado?',
            
        }

restaurants/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required, permission_required
# Create your views here.
from django.http import HttpResponse, HttpRequest
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from .models import Restaurant, Resenha, Reserva
from .forms import RestaurantForm, ResenhaForm, ReservaForm, ReservaUpdateForm
from django.contrib import messages


def detail_restaurant(request: HttpRequest, restaurant_id) -> HttpResponse:
    restaurant = get_object_or_404(Restaurant, pk=restaurant_id)
    

    context = {'restaurant': restaurant}
    return render(request, 'restaurants/detail.html', context)


def meu_restaurant(request,user_id):
    context= {}
    search_list = Restaurant.objects.filter(author_id=user_id)
    if len(search_list) == 1:
        restaurant = get_object_or_404(Restaurant, author_id=user_id)
        context = {'restaurant': restaurant}
    return render(request, 'restaurants/meurestaurante.html', context)

    

class RestaurantListView(generic.ListView):
    model = Restaurant
    template_name = 'restaurants/index.html'


def search_restaurants(request):

    context = {}
    if request.GET.get('query', False):
        search_term = request.GET['query'].lower()
        search_list = Restaurant.objects.filter(name__icontains=search_term)
        context = {"search_list": search_list,}

    if request.GET.get('query2', False):
        search_term = request.GET['query2'].lower()
        search_list = Restaurant.objects.filter(comida__icontains=search_term)
        context = {"search_list": search_list,}
    else:
        restaurant_list = Restaurant.objects.all()
        context = {"restaurant_list":restaurant_list}
    return render(request, 'restaurants/search.html', context)
    
@login_required
@permission_required('restaurants.add_restaurant')
def create_restaurant(request):
    if request.method == 'POST':
        form = RestaurantForm(request.POST)
        if form.is_valid():
            restaurant_name = form.cleaned_data['name']
            restaurant_author_id = request.user.id
            restaurant_poster_url = form.cleaned_data['poster_url']
            restaurant_endereco = form.cleaned_data['endereco']
            restaurant_comida = form.cleaned_data['comida']
            restaurant_preco = form.cleaned_data['preco']
            restaurant_text = form.cleaned_data['text']
            restaurant = Restaurant(name=restaurant_name,                        
                          poster_url=restaurant_poster_url,
                          author_id=restaurant_author_id,
                          endereco=restaurant_endereco,
                          comida=restaurant_comida,
                          preco=restaurant_preco,
                          text = restaurant_text)
            restaurant.save()
            context = {'restaurant': restaurant}
            return render(request, 'restaurants/meurestaurante.html', context)

    else:
        form = RestaurantForm()
    context = {'form': form}
    return render(request, 'restaurants/create.html', context)


def update_restaurant(request, restaurant_id):
    restaurant = get_object_or_404(Restaurant, pk=restaurant_id)

    if request.method == "POST":
        form = RestaurantForm(request.POST)
        if form.is_valid():
            restaurant.name = form.cleaned_data['name']
            restaurant.poster_url = form.cleaned_data['poster_url']
            restaurant.endereco = form.cleaned_data['endereco']
            restaurant.comida = form.cleaned_data['comida']
            restaurant.preco = form.cleaned_data['preco']
            restaurant.text = form.cleaned_data['text']
            restaurant.save()
            context = {'restaurant': restaurant}
            return render(request, 'restaurants/meurestaurante.html', context)
    else:
        form = RestaurantForm(
            initial={
                'name': restaurant.name,
                'poster_url': restaurant.poster_url,
                'endereço':restaurant.endereco,
                'comida':restaurant.comida,
                'preco':restaurant.preco,
                'text':restaurant.text
            })

    context = {'restaurant': restaurant, 'form': form}
    return render(request, 'restaurants/update.html', context)

def delete_restaurant(request, restaurant_id):
    restaurant = get_object_or_404(Restaurant, pk=restaurant_id)

    if request.method == "POST":
        restaurant.delete()
        context={'restaurant': None}
        return render(request, 'restaurants/meurestaurante.html', context)

    context = {'restaurant':restaurant}
    return render(request, 'restaurants/delete.html', context)

@login_required
@permission_required('restaurants.add_resenha')
def create_resenha(request, restaurant_id):
    restaurant = get_object_or_404(Restaurant, pk=restaurant_id)
    if request.method == 'POST':
        form = ResenhaForm(request.POST)
        if form.is_valid():
            resenha_author = request.user
            resenha_text = form.cleaned_data['text']
            resenha_rating = form.cleaned_data['rating']
            resenha = Resenha(author=resenha_author,
                            text=resenha_text,
                            restaurant=restaurant,
                            rating=resenha_rating)
            resenha.save()
            restaurant.avr= restaurant.average_rating()
            restaurant.save()
            return HttpResponseRedirect(
                reverse('restaurants:detail', args=(restaurant_id, )))
    else:
        form = ResenhaForm()
    context = {'form': form, 'restaurant': restaurant}
    return render(request, 'restaurants/resenha.html', context)

def reserva_restaurant(request: HttpRequest, restaurant_id) -> HttpResponse:
    restaurant = get_object_or_404(Restaurant, pk=restaurant_id)
    

    context = {'restaurant': restaurant}
    return render(request, 'restaurants/reserva.html', context)

@login_required
@permission_required('restaurants.add_reserva')
def create_reserva(request, restaurant_id):
    restaurant = get_object_or_404(Restaurant, pk=restaurant_id)
    if request.method == 'POST':
        form = ReservaForm(request.POST)
        if form.is_valid():
            reserva_cliente = request.user
            reserva_cpf = form.cleaned_data['cpf']
            reserva_np = form.cleaned_data['np']
            reserva_reserva = form.cleaned_data['reserva']
            reserva = Reserva(cliente=reserva_cliente,
                            cpf=reserva_cpf,
                            restaurant=restaurant,
                            np=reserva_np,
                            reserva= reserva_reserva)
            reserva.save()
            return HttpResponseRedirect(
                reverse('restaurants:reserva', args=(restaurant_id, )))
    else:
        form = ReservaForm()
    context = {'form': form, 'restaurant': restaurant}
    return render(request, 'restaurants/reservacreate.html', context)

@login_required
@permission_required('restaurants.change_reserva')
def update_reserva(request, reserva_id):
    reserva= get_object_or_404(Reserva, pk=reserva_id)
    restaurant = get_object_or_404(Restaurant, pk=reserva.restaurant.id)
    if request.method == "POST":
        form = ReservaUpdateForm(request.POST)
        if form.is_valid():

            reserva.standby=1
            reserva.aprove= form.cleaned_data['aprove']
            

            reserva.save()
            context = {'restaurant': restaurant}
            return render(request, 'restaurants/reserva.html', context)
    else:
        form = ReservaUpdateForm(
            initial={
                'aprove':reserva.aprove,
                
            })

    context = {'reserva': reserva, 'form': form}
    return render(request, 'restaurants/reservaup.html', context)

def minhas_reserva(request, user_id):
    context= {}
    reserva_list = Reserva.objects.filter(cliente_id=user_id)
    context = {'reserva_list': reserva_list}
    return render(request, 'restaurants/minhasreservas.html', context)
# @login_required
# @permission_required('restaurants.add_resenha')
# def submit_resenha(request, restaurant_id):
#     url = request.META.get('HTTP_REFERER')
#     if request.method == 'POST':
#         try:
#             resenhas = Resenha.objects.get(author__id=request.user.id, restaurant__id=restaurant_id)
#             form = ResenhaForm(request.POST, instance=resenhas)
#             form.save()
#             messages.success(request, 'Thank you! Your review has been updated.')
#             return redirect(url)
#         except Resenha.DoesNotExist:
#             form = ResenhaForm(request.POST)
#             if form.is_valid():
#                 data = Resenha()
#                 data.rating = form.cleaned_data['rating']
#                 data.text = form.cleaned_data['text']
                
#                 data.restaurant_id = restaurant_id
#                 data.author_id = request.user.id
#                 data.save()
#                 messages.success(request, 'Thank you! Your review has been submitted.')
#                 return redirect(url)

restaurants/templates/restaurants/create.html
{% extends 'base.html' %}

{% block content %}
<h2>Inserir Novo Restaurante</h2>
<form method="POST" action="{% url 'restaurants:create' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %}

restaurants/templates/restaurants/delete.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'restaurants:delete' restaurant.id %}" method="post">
    {% csrf_token %}
    <p>
        Você tem certeza que deseja apagar o restaurante "{{ restaurant.name }}"?
    </p>
    <button type="submit">Apagar</button>
</form>

{% endblock content %}

restaurants/templates/restaurants/detail.html
{% extends 'base.html' %}

{% block title %}
{{ restaurant.name }} 
{% endblock title %}

{% block content %}

<h2>{{ restaurant.name }}</h2>

<section class="dados-de-filme">
    <img src="{{ restaurant.poster_url }}" alt="Poster do restaurante {{ restaurant.name}}">
    <ul>
        <li>Nome: {{ restaurant.name }}</li>
        
        <li class="card-title2">
            <i>Nota média:</i> 
            {% if restaurant.average_rating > 0.5 %} 
            <i class="fa fa-star" aria-hidden="true" width = "500%"></i>
            {% endif %}
            {% if restaurant.average_rating > 1.5 %} 
            <i class="fa fa-star" aria-hidden="true"></i>
            {% endif %}
            {% if restaurant.average_rating > 2.5 %} 
            <i class="fa fa-star" aria-hidden="true"></i>
            {% endif %}
            {% if restaurant.average_rating > 3.5 %} 
            <i class="fa fa-star" aria-hidden="true"></i>
            {% endif %}
            {% if restaurant.average_rating > 4.5 %} 
            <i class="fa fa-star" aria-hidden="true"></i>
            {% endif %}
            <i> {{ restaurant.avr|floatformat:1}}<i> 
        </li>
        <hr>
        <li>Endereço: {{ restaurant.endereco }}</li>
        <li>Tipo de comida: {{ restaurant.comida }}</li>
        <li>Faixa de preço: {{ restaurant.preco }}</li>
        <!-- {% if restaurant.author_id == user.id %} -->
        <!-- <li><a href="{% url 'restaurants:update' restaurant.id %}">Editar</a></li> -->
        <!-- <li><a href="{% url 'restaurants:delete' restaurant.id %}">Apagar</a></li> -->
        <!-- {%endif%} -->
        <hr>
        <li><textarea name="text" rows="8" class="form-control" disabled="True">{{ restaurant.text }}</textarea></li>
      
    </ul>
</section>
{% include 'includes/alerts.html'%}

<hr>
<a href="{% url 'restaurants:reserva' restaurant.pk %}"><button>Reserva</button></a>
<a href="{% url 'restaurants:resenha' restaurant.pk %}"><button>Crie sua Resenha</button></a>
<hr>
<section>
    <header>
        <h3>Resenhas</h3>
    </header>
    <ul>
        {% if restaurant.resenha_set.all %}
            {% for resenha in restaurant.resenha_set.all|dictsortreversed:"data" %}
                <figure>
                    <blockquote>
                        "{{ resenha.text }}"
                    </blockquote>
                    <figcaption>—{{ resenha.author }},{{resenha.data|date:"SHORT_DATE_FORMAT"}}, Nota: {{ resenha.rating }}
                </figure>
            {% endfor %}
        {% else %}
            <p>Ainda não existe nenhuma resenha para este restaurante.</p>
        {% endif %}
    </ul>
    

</section>

{% endblock content %}

restaurants/templates/restaurants/index.html
{% extends 'base.html' %}

{% block content %}
<h2>Todos os Filmes</h2>
<section>
    <p>Muitos resultados? <a href="{% url 'restaurants:search' %}">Buscar Restaurantes</a></p>
    <p>Não encontrou o filme? <a href="{% url 'restaurants:create' %}">Adicionar Novo Restaurante</a></p>
</section>
{% if restaurant_list %}
<section class="lista-de-cards">
    {% for restaurant in restaurant_list %}
    <article class="card">
        <a href="{% url 'restaurants:detail' restaurant.id %}"><img src="{{ restaurant.poster_url }}"
            alt="Poster do filme {{ restaurant.name}}"></a>
        <p>{{ restaurant.name }} </p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum restaurante.</p>
{% endif %}

{% endblock content %}

restaurants/templates/restaurants/meurestaurante.html
{% extends 'base.html' %}

{% block title %}
{{ restaurant.name }} 
{% endblock title %}

{% block content %}
{% if restaurant %}
<h2>{{ restaurant.name }}</h2>

<section class="dados-de-filme">
    <img src="{{ restaurant.poster_url }}" alt="Poster do restaurante {{ restaurant.name}}">
    <ul>
        <li>Nome: {{ restaurant.name }}</li>
        <li class="card-title2">Avarage rating:
            {% if restaurant.average_rating > 0.5 %} 
            <i class="fa fa-star" aria-hidden="true" width = "500%"></i>
            {% endif %}
            {% if restaurant.average_rating > 1.5 %} 
            <i class="fa fa-star" aria-hidden="true"></i>
            {% endif %}
            {% if restaurant.average_rating > 2.5 %} 
            <i class="fa fa-star" aria-hidden="true"></i>
            {% endif %}
            {% if restaurant.average_rating > 3.5 %} 
            <i class="fa fa-star" aria-hidden="true"></i>
            {% endif %}
            {% if restaurant.average_rating > 4.5 %} 
            <i class="fa fa-star" aria-hidden="true"></i>
            {% endif %}
            &nbsp
            <i> {{ restaurant.avr|floatformat:2 }}<i> 
        </li>
        <li>Endereço: {{ restaurant.endereco }}</li>
        <li>Tipo de comida: {{ restaurant.comida }}</li>
        <li>Faixa de preço: {{ restaurant.preco }}</li>
        <li><textarea name="text" rows="8" class="form-control" disabled="True">{{ restaurant.text }}</textarea></li>
        {% if restaurant.author_id == user.id %}
        <li><a href="{% url 'restaurants:update' restaurant.id %}">Editar</a></li>
        <li><a href="{% url 'restaurants:delete' restaurant.id %}">Apagar</a></li>
        {%endif%}
    </ul>
</section>

<hr>
<a href="{% url 'restaurants:reserva' restaurant.pk %}"><button>Reserva</button></a>
<hr>
<section>
    <header>
        <h3>Resenhas</h3>
    </header>
    <ul>
        {% if restaurant.resenha_set.all %}
            {% for resenha in restaurant.resenha_set.all %}
                <figure>
                    <blockquote>
                        "{{ resenha.text }}"
                    </blockquote>
                    <figcaption>—{{ resenha.author }}, Nota:{{ resenha.rating}}, {{ resenha.data }}
                </figure>
            {% endfor %}
        {% else %}
            <p>Ainda não existe nenhuma resenha para este restaurante.</p>
        {% endif %}
    </ul>


</section>
{% else %}
<h>Não tem Restaurante ainda?</h>
<h>Bora criar?</h>
<a href="{% url 'restaurants:create' %}">Criar restaurante</a></p>
{% endif %}


{% endblock content %}

restaurants/templates/restaurants/minhasreservas.html
{% extends 'base.html' %}

{% block title %}
{{ user.first_name }} {{ user.last_name }} 
{% endblock title %}

{% block content %}

<h1>Minhas Reservas</h1>
{% for reserva in reserva_list %}
    <section>

        {% if reserva.standby %}
            {% if reserva.aprove %}
            <hr>
                <figure class="aprovada">
                    <h5>Sua reserva foi aprovada!</h5>
                    <blockquote>
                        {{ reserva.np }} &nbsp Pessoas &nbsp {{reserva.reserva|date:"SHORT_DATE_FORMAT"}}
                    </blockquote>
                    <figcaption>—{{ reserva.cliente }},Data de upload: {{ reserva.data_up }}
                </figure>
            {% else %} 
                <hr>
                <figure class="desaprovada">
                    <h5>Infelizmente sua reserva não foi aprovada</h5>
                    <blockquote>
                        {{ reserva.np }} &nbsp Pessoas &nbsp {{reserva.reserva|date:"SHORT_DATE_FORMAT"}}
                    </blockquote>
                    <figcaption>—{{ reserva.cliente }},Data de upload: {{ reserva.data_up }}
                </figure>
            {% endif %}

        {% else %} 
            <hr>
            <figure class="nvista">
                <h5>Aguarde, sua reserva não foi vista ainda</h5>
                <blockquote>
                    {{ reserva.np }} &nbsp Pessoas &nbsp {{reserva.reserva|date:"SHORT_DATE_FORMAT"}}
                </blockquote>
                <figcaption>—{{ reserva.cliente }},Data de upload: {{ reserva.data_up }}
            </figure>
        {% endif %}

    </section>
{% endfor %}
{% endblock content %}

restaurants/templates/restaurants/resenha.html
{% extends 'base.html' %}

{% block content %}
<h2>Resenhar Restaurante {{ restaurant.name }} </h2>

<form action="{% url 'restaurants:resenha' restaurant.id %}" method="post">
    {% csrf_token %}
    <h5>Escreva sua Resenha</h5>
    <div class="rate">
        <input type="radio" name="rating" id="rating10" value="5" required /><label for="rating10" title="5"></label>
        <input type="radio" name="rating" id="rating9" value="4.5" required /><label for="rating9" title="4.5" class="half"></label>
        <input type="radio" name="rating" id="rating8" value="4" required /><label for="rating8" title="4"></label>
        <input type="radio" name="rating" id="rating7" value="3.5" required /><label for="rating7" title="3.5" class="half"></label>
        <input type="radio" name="rating" id="rating6" value="3" required /><label for="rating6" title="3"></label>
        <input type="radio" name="rating" id="rating5" value="2.5" required /><label for="rating5" title="2.5" class="half"></label>
        <input type="radio" name="rating" id="rating4" value="2" required /><label for="rating4" title="2"></label>
        <input type="radio" name="rating" id="rating3" value="1.5" required /><label for="rating3" title="1.5" class="half"></label>
        <input type="radio" name="rating" id="rating2" value="1" required /><label for="rating2" title="1"></label>
        <input type="radio" name="rating" id="rating1" value="0.5" required /><label for="rating1" title="0.5" class="half"></label>
    </div>
    <br> 
    Review Title:
    <textarea name="text" rows="4" class="form-control"></textarea>
    <br>
    <button type="submit">Postar Resenha</button>
</form>

<p><a href="{% url 'restaurants:detail' restaurant.id %}">Voltar para a página do restaurante</a></p>
{% endblock content %}

restaurants/templates/restaurants/reserva.html
{% extends 'base.html' %}

{% block title %}
{{ restaurant.name }} 
{% endblock title %}

{% block content %}

<section>
    <header>
        <h3>Reservas</h3>
        {% if user.id == restaurant.author_id %}
                <h3>Suas Reservas não vistas</h3>
        {% endif %}
    </header>
    {% if perms.restaurants.add_reserva %}
    <a href="{% url 'restaurants:reservacreate' restaurant.pk %}"><button>Fazer sua Reserva</button></a>
    {% endif %}
    <ul>
        {% if restaurant.reserva_set.all %}
            {% for reserva in restaurant.reserva_set.all|dictsortreversed:"data_up" %}
                {% if user.id == reserva.cliente.id %}
                    {% if reserva.standby %}
                        {% if reserva.aprove %}
                        <hr>
                            <figure class="aprovada">
                                <h5>Sua reserva foi aprovada!</h5>
                                <blockquote>
                                    {{ reserva.np }} &nbsp Pessoas &nbsp {{reserva.reserva|date:"SHORT_DATE_FORMAT"}}
                                </blockquote>
                                <figcaption>—{{ reserva.cliente }},Data de upload: {{ reserva.data_up }}
                            </figure>
                        {% else %} 
                            <hr>
                            <figure class="desaprovada">
                                <h5>Infelizmente sua reserva não foi aprovada</h5>
                                <blockquote>
                                    {{ reserva.np }} &nbsp Pessoas &nbsp {{reserva.reserva|date:"SHORT_DATE_FORMAT"}}
                                </blockquote>
                                <figcaption>—{{ reserva.cliente }},Data de upload: {{ reserva.data_up }}
                            </figure>
                        {% endif %}

                    {% else %} 
                    <hr>
                    <figure class="nvista">
                        <h5>Aguarde, sua reserva não foi vista ainda</h5>
                        <blockquote>
                            {{ reserva.np }} &nbsp Pessoas &nbsp {{reserva.reserva|date:"SHORT_DATE_FORMAT"}}
                        </blockquote>
                        <figcaption>—{{ reserva.cliente }},Data de upload: {{ reserva.data_up }}
                    </figure>
                    {% endif %}
                {% endif %}
                {% if user.id == restaurant.author_id %}
                
                    {% if reserva.standby == False %}
                        <hr>
                        <figure>
                            <blockquote>
                                {{ reserva.np }} &nbsp Pessoas &nbsp {{reserva.reserva|date:"SHORT_DATE_FORMAT"}}
                            </blockquote>
                            <figcaption>—{{ reserva.cliente }},Data de upload: {{ reserva.data_up }}
                                <a href="{% url 'restaurants:reservaup' reserva.pk %}"><button>Editar</button></a>
                        </figure>
                    {% endif %}
                {% endif %}
            {% endfor %}
        {% else %}
            <p>Ainda não existe nenhuma reserva para este restaurante.</p>
        {% endif %}
    </ul>
    

</section>
<p><a href="{% url 'restaurants:detail' restaurant.id %}">Voltar para a página do restaurante</a></p>
{% endblock content %}

restaurants/templates/restaurants/reservacreate.html
{% extends 'base.html' %}

{% block content %}
<h2>Criar reserva</h2>
<form method="POST" action="{% url 'restaurants:reservacreate' restaurant.pk %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %}

restaurants/templates/restaurants/reservaup.html
{% extends 'base.html' %}

{% block content %}
<h2>Avaliar Reserva</h2>
<li>Nome: {{ reserva.cliente}}</li>
<li>CPF: {{ reserva.cpf}}</li>
<li>Número de pessoas: {{ reserva.np}}</li>
<li>Data da reserva: {{ reserva.reserva}}</li>
<form method="POST" action="{% url 'restaurants:reservaup' reserva.pk %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Atualizar</button>
</form>

{% endblock content %}

restaurants/templates/restaurants/update.html
{% extends 'base.html' %}

{% block content %}
<h2>Atualizar Dados do Restaurante {{ restaurant.name }}</h2>
<form method="POST" action="{% url 'restaurants:update' restaurant.id%}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Atualizar</button>
</form>

{% endblock content %}