irdb/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('staticpages.urls')),
    path('restaurants/', include('restaurants.urls')), # adicionar esta linha
    path('accounts/', include('accounts.urls')), # adicionar esta linha
    path('accounts/', include('django.contrib.auth.urls')), # adicione esta linha
    path('admin/', admin.site.urls),
]

restaurants/urls.py
from django.urls import path

from . import views


app_name = 'restaurants'
urlpatterns = [
    path('', views.RestaurantListView.as_view(), name='index'),
    path('search/', views.search_restaurants , name='search'),
    path('create/', views.create_restaurant, name='create'),
    path('minhasreservas/<int:user_id>/', views.minhas_reserva, name='minhasreservas'),
    path('<int:restaurant_id>/reserva/', views.reserva_restaurant, name='reserva'),
    path('<int:restaurant_id>/reservacreate', views.create_reserva, name='reservacreate'),
    path('<int:reserva_id>/reservaup', views.update_reserva, name='reservaup'),
    path('meurestaurante/<int:user_id>/', views.meu_restaurant, name='meurestaurante'),
    path('<int:restaurant_id>/', views.detail_restaurant, name='detail'),
    #path('submit_resenha/<int:restaurant_id>/', views.submit_resenha, name='submit_resenha'),
    path('update/<int:restaurant_id>/', views.update_restaurant, name='update'),
    path('delete/<int:restaurant_id>/', views.delete_restaurant, name='delete'),
    path('<int:restaurant_id>/resenha/', views.create_resenha, name='resenha'),
]

restaurants/models.py
from django.db import models

# Create your models here.
from django.conf import settings
from django.db.models import Avg
from django.contrib.auth.models import User
from cpf_field.models import CPFField

class Restaurant(models.Model):
    name = models.CharField(max_length=255)
    poster_url = models.URLField(max_length=200, null=True)
    author_id = models.IntegerField(default=0)
    endereco = models.CharField(max_length=255, blank= True)
    comida = models.CharField(max_length=255, blank= True)
    preco = models.CharField(max_length=255, blank= True)
    text = models.TextField(max_length=500, blank= True)
    avr = models.FloatField(default=0)
    
    def average_rating(self) -> float:
        return Resenha.objects.filter(restaurant=self).aggregate(Avg("rating"))["rating__avg"] or 0

    def __str__(self):
        return f'{self.name}'
    

class Resenha(models.Model):
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    text = models.TextField(max_length=500, blank= True)
    likes = models.IntegerField(default=0)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    rating = models.FloatField(default=0)
    data=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'"{self.text}" - {self.author.username}'

class Reserva (models.Model):
    cliente = models.ForeignKey(User,on_delete=models.CASCADE)
    cpf = CPFField('cpf')
    np = models.IntegerField(default=0)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    data_up=models.DateTimeField(auto_now_add=True)
    reserva=models.DateTimeField('%Y-%m-%d %H:%M')
    standby = models.BooleanField(default=False)
    aprove = models.BooleanField(default=False)

    def __str__(self):
        return f'"{self.cliente}" - {self.restaurant}'

templates/base.html
{% load static %} <!-- adicione esta linha -->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} | Internet Restaurant Database!
    </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" /> <!-- adicione esta linha -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"> <!-- adicione esta linha -->
    <link rel="stylesheet" type="text/css" href="{% static 'rate.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    
</head>

<body class="fundo">
    <header id="cabecalho-principal">
        <a href="{% url 'index' %}"> <img src="{% static 'logo.png' %}" width="50%"> </a> <!-- adicione esta linha -->
        <nav id="navegacao-principal">
            <ul>
                {% if user.is_authenticated %}
                <li> Logado com {{ user.username }}({{ user.id }}) </li>
                <li><a href="{% url 'logout' %}">Log out</a></li>
                {% else %}
                <li><a href="{% url 'login' %}">Log in</a></li>
                {% endif %}
            
            
                <li><a href="{% url 'restaurants:search' %}">Buscar</a></li>
                {% if perms.restaurants.add_restaurant %}
                <li><a href="{% url 'restaurants:meurestaurante' user.id %}">Meu Restaurante</a></li>
                {% endif %}
                {% if perms.restaurants.add_reserva%}
                <li><a href="{% url 'restaurants:minhasreservas' user.id %}">Minhas Reservas</a></li>
                {% endif %}
                <!-- <li><a href="{% url 'restaurants:index' %}">Restaurantes</a></li>  -->
                <li><a href="{% url 'about' %}">Sobre</a></li>
            </ul>
        </nav>

    </header>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>
            <small>© 2022 by IRDb.com</small>
        </p>
    </footer>
</body>

</html>